#!/usr/bin/env python3
"""Build a sanitized, screenshot-only fixture using the production portal CSS."""

from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "Index.html"
OUTPUT = ROOT / "tmp" / "visual_fixture" / "index.html"


def main():
    source = SOURCE.read_text(encoding="utf-8")
    match = re.search(r"<style>(.*?)</style>", source, re.S)
    if not match:
        raise RuntimeError("Could not extract production portal styles")
    css = match.group(1)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(PAGE.replace("/*__PORTAL_CSS__*/", css), encoding="utf-8")
    print(OUTPUT)


PAGE = r'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Classroom Creation Request - Visual Walkthrough</title>
  <style>
  /*__PORTAL_CSS__*/
  .fixture-note { margin: 0 0 1rem; padding: .7rem .85rem; color: #3f3fbf; background: #eeeeff; border-radius: .5rem; font-size: .86rem; font-weight: 650; }
  .fixture-tag { display:inline-block; margin-bottom:.7rem; padding:.26rem .55rem; color:#fff; background:#6161ff; border-radius:999px; font-size:.72rem; font-weight:700; text-transform:uppercase; letter-spacing:.04em; }
  .mock-board { overflow:hidden; background:#fff; border:1px solid #d0d4e4; border-radius:.7rem; box-shadow:0 8px 28px rgba(31,35,48,.08); }
  .mock-board-head { display:flex; align-items:center; justify-content:space-between; padding:1.1rem 1.25rem; border-bottom:1px solid #d0d4e4; }
  .mock-board h1 { margin:0; font-size:1.55rem; }
  .mock-toolbar { display:flex; gap:.5rem; }
  .mock-pill { padding:.4rem .65rem; border:1px solid #d0d4e4; border-radius:.35rem; color:#323338; background:#fff; font-size:.78rem; }
  .board-grid { display:grid; grid-template-columns:2fr 1fr 1.1fr 1.1fr 1.25fr .9fr 1fr; min-width:1080px; }
  .board-cell { min-height:3.3rem; padding:.65rem .7rem; border-right:1px solid #d0d4e4; border-bottom:1px solid #d0d4e4; display:flex; align-items:center; font-size:.78rem; }
  .board-cell.header { min-height:2.45rem; color:#676879; background:#f6f7fb; font-weight:700; }
  .board-cell.item { border-left:6px solid #00c875; font-weight:700; }
  .status-chip { display:inline-block; width:100%; padding:.42rem .45rem; color:#fff; background:#fdab3d; border-radius:.25rem; text-align:center; font-weight:700; }
  .status-chip.green { background:#00c875; }
  .status-chip.purple { background:#a25ddc; }
  .mock-detail { display:grid; grid-template-columns:1fr 1fr; gap:.8rem 1.2rem; padding:1.15rem 1.25rem 1.4rem; }
  .mock-detail .wide { grid-column:span 2; }
  .audit-shell { background:#fff; border:1px solid #dadce0; border-radius:.6rem; overflow:hidden; box-shadow:0 8px 28px rgba(31,35,48,.08); }
  .audit-title { padding:1rem 1.2rem; font-size:1.25rem; font-weight:700; border-bottom:1px solid #dadce0; }
  .audit-tabs { display:flex; gap:.25rem; padding:.55rem 1rem; background:#f8f9fa; border-bottom:1px solid #dadce0; }
  .audit-tab { padding:.35rem .7rem; border-radius:.25rem; font-size:.78rem; }
  .audit-tab.active { color:#fff; background:#6161ff; }
  .audit-grid { display:grid; grid-template-columns:1.1fr 1fr 1.2fr 1.2fr 1.3fr 2fr; }
  .audit-cell { padding:.55rem .62rem; border-right:1px solid #e1e3e7; border-bottom:1px solid #e1e3e7; font-size:.71rem; overflow-wrap:anywhere; }
  .audit-cell.header { color:#fff; background:#6161ff; font-weight:700; }
  .audit-json { margin:1rem; padding:.9rem; background:#f6f7fb; border-left:4px solid #6161ff; border-radius:.35rem; font: .72rem/1.45 ui-monospace,SFMono-Regular,Menlo,monospace; overflow-wrap:anywhere; }
  .assignment-flow { display:grid; grid-template-columns:1fr auto 1fr auto 1fr; align-items:center; gap:.7rem; margin:1.2rem 0; }
  .assignment-step { min-height:5.8rem; padding:1rem; border:1px solid #d0d4e4; border-radius:.65rem; background:#fff; }
  .assignment-step strong { display:block; margin-bottom:.4rem; }
  .assignment-arrow { color:#6161ff; font-size:1.35rem; font-weight:800; }
  .notification-layout { display:grid; grid-template-columns:1fr 1fr; gap:1.2rem; }
  .email-mock,.chat-shell { overflow:hidden; border:1px solid #d0d4e4; border-radius:.75rem; background:#fff; box-shadow:0 8px 28px rgba(31,35,48,.08); }
  .email-top { padding:.85rem 1rem; color:#fff; background:#6161ff; font-weight:750; }
  .email-body { padding:1rem 1.1rem; }
  .email-facts { display:grid; grid-template-columns:1fr 1fr; gap:.7rem; margin:1rem 0; }
  .chat-shell { padding:.65rem; background:#202124; color:#e8eaed; }
  .chat-card { overflow:hidden; border:1px solid #5f6368; border-radius:.65rem; background:#292a2d; }
  .chat-head,.chat-section,.chat-action { padding:.8rem .9rem; border-bottom:1px solid #5f6368; }
  .chat-head strong { font-size:1rem; }
  .chat-section:last-of-type { border-bottom:1px solid #5f6368; }
  .chat-label { color:#bdc1c6; font-size:.72rem; text-transform:uppercase; letter-spacing:.04em; }
  .chat-button { display:block; padding:.48rem .7rem; border:1px solid #8ab4f8; border-radius:999px; color:#8ab4f8; text-align:center; font-weight:700; }
  .privacy { display:flex; align-items:flex-start; gap:.7rem; margin-top:1rem; padding:.85rem; color:#8a5b00; background:#fff7df; border-radius:.5rem; }
  @media (max-width:800px){.board-grid{min-width:0;grid-template-columns:1.6fr 1fr 1fr}.board-cell:nth-child(7n+4),.board-cell:nth-child(7n+5),.board-cell:nth-child(7n+6),.board-cell:nth-child(7n+7){display:none}.audit-grid{grid-template-columns:1fr 1fr 1fr}.audit-cell:nth-child(6n+4),.audit-cell:nth-child(6n+5),.audit-cell:nth-child(6n+6){display:none}.notification-layout{grid-template-columns:1fr}.assignment-flow{grid-template-columns:1fr}.assignment-arrow{transform:rotate(90deg);text-align:center}}
  </style>
</head>
<body>
  <div class="app">
    <header class="topbar">
      <div class="brand"><span class="brand-mark">K</span><span>Classroom Creation</span></div>
      <div class="source">Kreyco Tech Support</div>
    </header>
    <main id="fixture" class="shell"></main>
  </div>
  <script>
  const sample = {
    school: 'Riverside Academy', classroom: 'French 6-8 - Section A',
    teacher: 'Jordan Lee', coach: 'Taylor Morgan', email: 'coach@example.org'
  };
  function esc(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function step(active){return `<nav class="steps" aria-label="Form progress">
    <div class="step ${active>0?'complete':''}" ${active===0?'aria-current="step"':''}><span class="step-number">${active>0?'✓':'1'}</span><span>Welcome</span></div>
    <div class="step ${active===1?'active':''}" ${active===1?'aria-current="step"':''}><span class="step-number">2</span><span>Request</span></div>
    <div class="step ${active===2?'active':''}" ${active===2?'aria-current="step"':''}><span class="step-number">3</span><span>Review</span></div>
  </nav>`;}
  function classCard(){return `<div class="class-card"><h3>${esc(sample.classroom)}</h3><p><strong>School:</strong> ${esc(sample.school)}</p><p><strong>Current teacher:</strong> ${esc(sample.teacher)}</p></div>`;}
  function field(label,value,help='',wide=false){return `<div class="field ${wide?'span-2':''}"><label class="label">${label}</label><div class="control" style="background:#fff">${esc(value)}</div>${help?`<p class="help">${help}</p>`:''}</div>`;}
  function summaryItem(label,value){return `<div><span class="review-label">${label}</span><span class="review-value">${esc(value)}</span></div>`;}
  function welcome(){return `${step(0)}<section class="panel active"><span class="fixture-tag">Coach walkthrough</span><h1>Classroom Creation Request</h1><p class="lede">Submit one request for one class. Your class link will always reopen its current draft or progress summary.</p><div class="notice"><p><strong>3-5 lessons per class section</strong> can be uploaded in one request.</p><p>Requests may take <strong>2-5 business days</strong> to complete. Please plan for this lead time.</p></div><label class="check-row"><input type="checkbox" checked><span>I understand the lesson limit and processing timeline.</span></label><div class="actions"><span></span><button class="button primary">Continue →</button></div></section>`;}
  function selectClass(){return `${step(1)}<section class="panel active"><span class="fixture-tag">Step 2 - choose a class</span><h2>Class and request details</h2><p class="lede">Choose the class, then complete its classroom details. The current teacher follows the Accounts assignment automatically.</p><div class="school-picker"><label class="label">School search</label><div class="control">Riverside</div><div class="fetch-state ready"><span>✓ Active schools ready.</span></div><label class="label">Active school</label><select class="control" size="4"><option selected>Riverside Academy - 3 available of 4</option><option>Riverside Preparatory School - 2 available of 2</option><option>Riverside Charter Academy - 1 available of 1</option></select><div class="picker-footer"><button class="button" disabled>← Previous</button><span class="help">Page 1 of 1 · 3 active schools</span><button class="button" disabled>Next →</button></div></div><div class="field" style="margin-top:1rem"><label class="label">Class <span class="required">*</span></label><select class="control"><option selected>${esc(sample.classroom)} - ${esc(sample.teacher)}</option></select><p class="help">Current teacher: ${esc(sample.teacher)}</p></div>${classCard()}<div class="actions"><button class="button">← Back</button><button class="button primary">Continue with this class →</button></div></section>`;}
  function details(){return `${step(1)}<section class="panel active"><span class="fixture-tag">Step 2 - request details</span><h2>Class and request details</h2>${classCard()}<div class="form-grid"><div class="assigned-contact"><div class="assigned-contact-row"><div class="field"><label class="label">Assigned coach</label><select class="control"><option>${esc(sample.coach)}</option></select><p class="help">The coach assignment comes from the selected teacher's Staff Directory item.</p></div><button class="button">Use a different contact</button></div></div>${field('Coach name *',sample.coach)}${field('Coach email *','Email on file in Monday','The assigned coach email stays private and receives notifications.')}${field('Language *','French')}${field('Grade level','6-8','Optional')}${field('Kreyco curriculum *','French Foundations - Level 2','This is a text field.',true)}${field('Classrooms needed by','September 15, 2026','Optional requested timeline; Tech may set a separate target completion date.')}</div><div class="actions"><button class="button">← Back</button><div class="actions-right"><button class="button">Save as draft</button><button class="button primary">Continue to platform details →</button></div></div></section>`;}
  function platforms(){return `${step(1)}<section class="panel active"><span class="fixture-tag">Step 2 - LMS and grading</span><h2>Classroom platform details</h2>${classCard()}<div class="form-grid">${field('Credentials (LMS)','Secure-share link provided','Use a password-manager secure-share link instead of a reusable password.',true)}${field('Verification needed for LMS?','Yes','Optional')}${field('Use Google Classroom for grading? *','No')}${field('Other grading platform','Canvas','Required when Google Classroom is not used.')} ${field('Credentials (grading platform)','Secure-share link provided','Credential contents will not appear in the progress summary.')} ${field('Schedule (check Smores)','Monday and Wednesday, Period 3','',true)}</div><div class="privacy"><strong>Privacy reminder</strong><span>Use secure-share links and keep the private coach portal link confidential.</span></div><div class="actions"><button class="button">← Back</button><div class="actions-right"><button class="button">Save as draft</button><button class="button primary">Review request →</button></div></div></section>`;}
  function review(){return `${step(2)}<section class="panel active"><span class="fixture-tag">Step 3 - review</span><h2>Review and submit</h2><p class="lede">Confirm the class-specific details before notifying Tech.</p><section class="review-section"><h3>Class</h3><div class="review-grid">${summaryItem('School',sample.school)}${summaryItem('Class',sample.classroom)}${summaryItem('Current teacher',sample.teacher)}</div></section><section class="review-section"><h3>Requester</h3><div class="review-grid">${summaryItem('Coach',sample.coach)}${summaryItem('Coach email','Email on file in Monday')}</div></section><section class="review-section"><h3>Classroom setup</h3><div class="review-grid">${summaryItem('Language','French')}${summaryItem('Grade level','6-8')}${summaryItem('Kreyco curriculum','French Foundations - Level 2')}${summaryItem('Classrooms needed by','September 15, 2026')}${summaryItem('LMS verification','Yes')}${summaryItem('Google Classroom grading','No')}${summaryItem('Other grading platform','Canvas')}${summaryItem('Credentials','Secure information provided')}${summaryItem('Schedule','Monday and Wednesday, Period 3')}</div></section><div class="actions"><button class="button">← Edit</button><div class="actions-right"><button class="button">Save as draft</button><button class="button success">Submit to Tech</button><button class="button primary">Submit &amp; add another class</button></div></div></section>`;}
  function saved(){return `<section class="panel active"><span class="fixture-tag">Draft saved</span><div class="banner"><strong>Draft saved</strong><p style="margin:.35rem 0 0">Tech has not been notified. Resume from the class row or the private coach link.</p></div><h2>${esc(sample.classroom)}</h2><p class="lede">CCR-13000000001 · ${esc(sample.school)}</p><div class="notice"><strong>Your reliable return point</strong><p>Use the Classroom Request Form link on this class's Accounts row whenever you need to continue.</p></div><div class="privacy"><strong>Keep the coach link private</strong><span>It permits editing and submission for this class.</span></div><div class="actions"><a class="button">Open class portal</a><button class="button primary">Continue editing</button></div></section>`;}
  function timeline(){return `<div class="timeline"><div class="milestone done">Sent to Tech</div><div class="milestone done">Under Review</div><div class="milestone active">In Progress</div><div class="milestone">Waiting for Information</div><div class="milestone">Ready for Verification</div><div class="milestone">Completed</div></div>`;}
  function coachSummary(){return `<section class="panel active"><span class="fixture-tag">Coach progress view</span><div class="summary-head"><div><span class="badge">In Progress</span><h1 style="margin-top:.7rem">${esc(sample.classroom)}</h1><p class="lede">CCR-13000000001</p></div><div class="actions-right"><button class="button">Edit request details</button><button class="button primary">Add another class</button><button class="button">Refresh status</button></div></div><div class="progress-track"><div class="progress-bar" style="width:55%"></div></div><p class="help">55% progress</p>${timeline()}<div class="notice"><strong>Latest update</strong><p style="margin:.35rem 0 0">Tech has created the LMS classroom and is configuring the grading connection.</p></div><div class="summary-grid">${summaryItem('School',sample.school)}${summaryItem('Current teacher',sample.teacher)}${summaryItem('Coach',sample.coach)}${summaryItem('Language','French')}${summaryItem('Grade level','6-8')}${summaryItem('Target completion','September 15, 2026')}${summaryItem('Submitted','September 8, 2026')}${summaryItem('Last coach update','September 10, 2026')}</div><section class="review-section" style="margin-top:1.5rem"><h2>Send additional information</h2><p class="lede">Send a note without changing the original request fields. Tech is notified.</p><label class="label">Additional information for Tech *</label><textarea class="control" placeholder="Describe the new information, correction, or follow-up"></textarea><div class="actions"><span></span><button class="button primary">Send information to Tech</button></div></section></section>`;}
  function teacherSummary(){return `<section class="panel active"><span class="fixture-tag">Teacher read-only view</span><div class="summary-head"><div><span class="badge">In Progress</span><h1 style="margin-top:.7rem">${esc(sample.classroom)}</h1><p class="lede">CCR-13000000001</p></div><button class="button">Refresh status</button></div><div class="fixture-note">This is a read-only progress view. Contact your coach if request details need to change.</div><div class="progress-track"><div class="progress-bar" style="width:55%"></div></div><p class="help">55% progress</p>${timeline()}<div class="notice"><strong>Latest update</strong><p style="margin:.35rem 0 0">Tech has created the LMS classroom and is configuring the grading connection.</p></div><div class="summary-grid">${summaryItem('School',sample.school)}${summaryItem('Current teacher',sample.teacher)}${summaryItem('Coach',sample.coach)}${summaryItem('Language','French')}${summaryItem('Grade level','6-8')}${summaryItem('Target completion','September 15, 2026')}${summaryItem('Submitted','September 8, 2026')}</div><div class="privacy"><strong>Teacher access</strong><span>The teacher can view progress but cannot edit coach-submitted fields or send updates from this link.</span></div></section>`;}
  function techBoard(){return `<section><span class="fixture-tag">Tech operations</span><div class="mock-board"><div class="mock-board-head"><div><h1>Classroom Creation Requests</h1><p class="help">Tech works on the same class-owned request item</p></div><div class="mock-toolbar"><span class="mock-pill">Filter</span><span class="mock-pill">Activity Log</span><span class="mock-pill">Automations</span></div></div><div class="board-grid"><div class="board-cell header">Item</div><div class="board-cell header">Request Status</div><div class="board-cell header">Current Teacher</div><div class="board-cell header">Assigned Coach</div><div class="board-cell header">Assigned Techs</div><div class="board-cell header">Target Date</div><div class="board-cell header">Notification State</div><div class="board-cell item">${esc(sample.classroom)}</div><div class="board-cell"><span class="status-chip">In Progress</span></div><div class="board-cell">${esc(sample.teacher)}</div><div class="board-cell">${esc(sample.coach)}</div><div class="board-cell">Alex Rivera, Blair Chen</div><div class="board-cell">Sep 15, 2026</div><div class="board-cell"><span class="status-chip purple">Pending</span></div></div><div class="mock-detail"><div>${summaryItem('Source Class',sample.classroom)}</div><div>${summaryItem('School Account',sample.school)}</div><div>${summaryItem('Public Progress Update','LMS classroom created; grading connection in progress.')}</div><div>${summaryItem('Internal Tech Notes','Visible to Tech only')}</div><div>${summaryItem('Notification Audience','Coach + Teacher')}</div><div>${summaryItem('Notification Message','The classroom is ready for the next verification step.')}</div><div class="wide notice"><strong>Two notification paths</strong><p>Notification State sends progress updates to Coach or Coach + Teacher. Assigned Techs uses a separate five-minute assignment queue.</p></div></div></div></section>`;}
  function audit(){return `<section><span class="fixture-tag">Audit and troubleshooting</span><div class="audit-shell"><div class="audit-title">Classroom Creation Request - Audit Log</div><div class="audit-tabs"><span class="audit-tab active">Audit Log</span><span class="audit-tab">Request Snapshots</span><span class="audit-tab">Configuration</span><span class="audit-tab">Tech Assignment Queue</span></div><div class="audit-grid"><div class="audit-cell header">Timestamp (UTC)</div><div class="audit-cell header">Action</div><div class="audit-cell header">Outcome</div><div class="audit-cell header">Request Item ID</div><div class="audit-cell header">Class</div><div class="audit-cell header">Message</div><div class="audit-cell">2026-09-03T14:32:08Z</div><div class="audit-cell">tech_assignment_observed</div><div class="audit-cell">queued</div><div class="audit-cell">13000000001</div><div class="audit-cell">${esc(sample.classroom)}</div><div class="audit-cell">Assignment changed; five-minute quiet period restarted.</div><div class="audit-cell">2026-09-03T14:37:12Z</div><div class="audit-cell">tech_assignment_delivered</div><div class="audit-cell">success</div><div class="audit-cell">13000000001</div><div class="audit-cell">${esc(sample.classroom)}</div><div class="audit-cell">New-assignee email and consolidated Chat card sent; sensitive values redacted.</div></div><div class="audit-json">{"eventId":"evt-example-001","category":"tech_assignment","action":"tech_assignment_delivered","outcome":"success","requestItemId":"13000000001","className":"French 6-8 - Section A","assigneeCount":2,"chatState":"sent","credentialState":"redacted"}</div></div><div class="privacy"><strong>Use both histories</strong><span>monday.com's Activity Log shows item changes; the Google Sheet adds sanitized JSON history and the durable Tech Assignment Queue.</span></div></section>`;}
  function techAssignment(){return `<section><span class="fixture-tag">Assigned Tech workflow</span><div class="mock-board"><div class="mock-board-head"><div><h1>Assign Tech support</h1><p class="help">One People column supports one or several technicians</p></div><span class="mock-pill">Tech Team · 881594</span></div><div class="mock-detail"><div>${summaryItem('Class',sample.classroom)}</div><div>${summaryItem('Assigned Techs','Alex Rivera, Blair Chen')}</div><div>${summaryItem('Request Status','Under Review')}</div><div>${summaryItem('Classrooms Needed By','September 15, 2026')}</div></div></div><div class="assignment-flow"><div class="assignment-step"><strong>1. Assignment changes</strong><span>Mariana selects Alex, then adds Blair a few minutes later.</span></div><span class="assignment-arrow">→</span><div class="assignment-step"><strong>2. Quiet period restarts</strong><span>The one-minute worker observes changes and waits five quiet minutes.</span></div><span class="assignment-arrow">→</span><div class="assignment-step"><strong>3. One consolidated delivery</strong><span>New assignees get individual emails; the Tech space gets one final Chat card.</span></div></div><div class="fixture-note">Retained assignees are not emailed again. Teams and people outside Tech Team are not notified.</div></section>`;}
  function assignmentNotifications(){return `<section><span class="fixture-tag">Assignment notifications</span><div class="notification-layout"><div class="email-mock"><div class="email-top">Kreyco Tech Support · Classroom request assigned</div><div class="email-body"><p>Hi Alex,</p><p>You have been assigned to a Google Classroom creation request.</p><div class="email-facts"><div>${summaryItem('Class',sample.classroom)}</div><div>${summaryItem('School',sample.school)}</div><div>${summaryItem('Teacher',sample.teacher)}</div><div>${summaryItem('Needed by','September 15, 2026')}</div></div><button class="button primary">Open request in monday.com</button><p class="help">Credential contents and private portal links are excluded.</p></div></div><div class="chat-shell"><div class="chat-card"><div class="chat-head"><strong>Classroom request assigned</strong><div class="help" style="color:#bdc1c6">CCR-13000000001 · Under Review</div></div><div class="chat-section"><div class="chat-label">Assignment</div><p><strong>Assigned Techs:</strong> Alex Rivera, Blair Chen</p><p><strong>Needed by:</strong> September 15, 2026</p></div><div class="chat-section"><div class="chat-label">Classroom</div><p><strong>School:</strong> ${esc(sample.school)}</p><p><strong>Class:</strong> ${esc(sample.classroom)}</p><p><strong>Teacher:</strong> ${esc(sample.teacher)}</p><p><strong>Coach:</strong> ${esc(sample.coach)}</p></div><div class="chat-action"><span class="chat-button">Open classroom request</span></div></div></div></div><div class="notice"><strong>Readable and consolidated</strong><p>The Chat card has no logo and posts only after the final assignment has been stable for five minutes.</p></div></section>`;}
  const views={welcome,select:selectClass,details,platforms,review,saved,'coach-summary':coachSummary,'teacher-summary':teacherSummary,'tech-board':techBoard,audit,'tech-assignment':techAssignment,'assignment-notifications':assignmentNotifications};
  const view=new URLSearchParams(location.search).get('view')||'welcome';
  document.getElementById('fixture').innerHTML=(views[view]||welcome)();
  document.body.dataset.view=view;
  </script>
</body>
</html>'''


if __name__ == "__main__":
    main()
